### ISSUE TITLE
Support changing working directory

### ISSUE THREAD

**Issue by samuelallan72** [canonical/create-pull-request#272]
Some use cases may require cloning a repository to a different path. It would be good to support changing the working directory of this action to support this case.

For example:

```
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
            repository: ${{ matrix.repository }}

      - name: Checkout the target repo
        uses: actions/checkout@v4
        with:
          path: target-repo

      # make changes

      - name: Create pull request
        uses: canonical/create-pull-request@main
        with:
          working-directory: target-repo
          ...

```
